### ISSUE TITLE
Review internal code chunks in README

### ISSUE THREAD

**Issue by stufield** [SomaLogic/SomaPlotr#19]
- the README.Rmd contains some figure generation code that may (or may not) want to expose to users
- the README mentions the use of `patchwork`, but we may not need to show/discuss that officially in the README
- unless we wish users to be able to follow and execute the code in the README locally
- clean up README for consistency and decide on "full disclosure" or "no disclosure" (right now it's a little of both)
- we may want to consider if `patchwork` is an official dependency (what are the downstream dependencies of `patchwork`?)
- do we wish to rely on `patchwork` in the future of the package as it evolves?

**Comment by amanda-hi** [comment]
I personally prefer `patchwork` over `gridExtra`, I think it takes care of a lot of scaling issues that are fiddly to resolve with `gridExtra`. It also has a very easy-to-use and intuitive interface. However, `patchwork` does have [more dependencies](https://cran.r-project.org/web/packages/patchwork/index.html) (`gridExtra` is pretty light, it imports just `gtable`, `grid`, `grDevices`, `graphics`, & `utils`). For a "Suggested" package that is just used in vignettes and the README, I don't see a huge issue with `patchwork`, but if we ultimately incorporate it into `SomaPlotr` package functions themselves, it might make more sense to stick with a tried & true package like `gridExtra` w/ less dependencies. As far as I know, creating "gridded" or composite figures (multiple plots stitched together) is not in the plan for `SomaPlotr`, right?
